[package]
name = "wayland-egl"
version = "0.29.0"
documentation = "https://smithay.github.io/wayland-rs/wayland_client/"
repository = "https://github.com/smithay/wayland-rs"
authors = ["Victor Berger <victor.berger@m4x.org>"]
license = "MIT"
edition = "2018"
categories = ["gui", "api-bindings"]
keywords = ["wayland", "client"]
description = "Bindings to libwayland-egl."
readme = "README.md"

[dependencies]
wayland-client = { version = "0.29.0", path = "../wayland-client", features = ["wayland-backend-sys"] }
wayland-sys = { version = "0.29.0", path="../wayland-sys", features = ["egl"] }
